### ISSUE TITLE
Routify doesn't work in sub directory.

### ISSUE THREAD

**Issue by nabeelalihashmi** [sveltech/svelte-filerouter#424]
How to make routify working in subdirectory?

like in DocumentRoot there is a folder `myproject` with structure like:

myproject
- app
- public
- frontend
- sv_assets

In output index I want to have 
`<script type="module" crossorigin src="/myproject/sv_assets/index.0718fa86.js"></script>
<link rel="modulepreload" href="/myproject/sv_assets/vendor.b3b54044.js">
<link rel="stylesheet" href="/myproject/sv_assets/index.3e37c916.css">
instead of 
`<script type="module" crossorigin src="/sv_assets/index.0718fa86.js"></script>
<link rel="modulepreload" href="/sv_assets/vendor.b3b54044.js">
<link rel="stylesheet" href="/sv_assets/index.3e37c916.css">`

and also, in built js files, ad myproject to avoid 404.
`Failed to load resource: the server responded with a status of 404 (Not Found)
/sv_assets/index.65166362.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by jakobrosenberg** [comment]
@nabeelalihashmi are you using v2 or v3?

**Comment by nabeelalihashmi** [comment]
> @nabeelalihashmi are you using v2 or v3?
@jakobrosenberg it is v2

**Comment by jakobrosenberg** [comment]
Sorry about the late follow up. Did you find a solution to this?

**Comment by HeyITGuyFixIt** [comment]
I have the same thing going on but in v3. I'm using [this example](https://v3.ci.routify.dev/docs#guide/concepts/url-rewrites) (with the typo fixed), and it still won't load. Not sure if vite needs to be configured differently.

**Comment by jakobrosenberg** [comment]
@HeyITGuyFixIt can you give me a step by step guide of what you're doing, what you expect to happen and what actually happens?

**Comment by HeyITGuyFixIt** [comment]
I am running Flask with Gunicorn, and have a folder called `admin` within my Flask project for Svelte. I tell Flask to serve the files in the `admin/dist` folder whenever someone browses to `/admin`. I'm running on Linux Mint, and have the LTS version of Node.JS installed.

I ran this command to create the Svelte/Routify project files:

```console
npx @roxi/routify@next create admin
```

Then I changed the App.svelte file to this based on the URL rewrite example:

<details><summary>App.svelte</summary>

```html
<script>
    import { Router } from '@roxi/routify'
    import routes from '../.routify/routes.default.js'

    /** @type {UrlRewrite}*/
    const urlRewrite = {
        toExternal: url => '/admin' + url,
        toInternal: url => url.replace(/\/admin/, ''),
    }
</script>

<Router {routes} {urlRewrite} />
```
</details>

BTW, the regex in the example doesn't escape the `/`, and I thought it was trying to escape it with a `^`, so I replaced the `^` with a `\`, but I'm just now realizing that I probably should add the `^` back in as well so that it reads `/^\/admin/`. I'll try that and let you know what happens in my next comment.

But with the way it is right now, I run `npm run build` in the admin directory. Then I start Flask and browse to `ipAddress/admin`, and it loads a blank white page. I go to the browser console and it shows that the scripts are still trying to be loaded from the root folder instead of from the `admin` folder, and thus are getting 404 errors.

It tries to load these addresses and gets 404 errors:

```
ipAddress/assets/index.a7ba7978.js
ipAddress/assets/vendor.fad5ec40.js
```

But it should be trying to get them from:

```
ipAddress/admin/assets/index.a7ba7978.js
ipAddress/admin/assets/vendor.fad5ec40.js
```

**Comment by HeyITGuyFixIt** [comment]
So adding the `^` didn't help. It still has the same outcome as I mentioned above.

**Comment by HeyITGuyFixIt** [comment]
I also tried your example from [here](https://github.com/roxiness/routify/discussions/406#discussioncomment-1633052) with `createRouter`, and I get the same outcome.

<details>
<summary>App.svelte</summary>

```html
<script>
    import { Router, createRouter } from '@roxi/routify'
    import routes from '../.routify/routes.default.js'

    const router = createRouter({
        routes,
        urlRewrite: {
            toExternal: url => '/admin' + url,
            toInternal: url => url.replace(/^\/admin/, ''),
        },
    })
</script>

<Router {router} />
```
</details>

**Comment by sophanox** [comment]
If this helps anyone, I've fixed this with:

```
<script>
  import { routes } from "../.routify/routes";
  import { Router } from "@roxi/routify";

  const config = {
    urlTransform: {
      /**
       *
       * @param url
       */
      apply: (url: string) => {
        if (url.startsWith("portal") === false) {
          return `/portal${url}`; // just to catch any instances where a link is missing the subdir
        }
        return url;
      },
      /**
       *
       * @param url
       */
      remove: (url: string) => url.toLowerCase(),
    },
  };

  // update the routes so they're prefaced with portal and case insensitive

  routes.forEach((r) => {
    r.path = "/portal" + r.path;
    r.regex = new RegExp(r.regex.replace("^/", "^/portal/"), "i");
  });
</script>
<Router config="{config}" routes="{routes}" />
```

where portal is my subdir

**Comment by jakobrosenberg** [comment]
Closing as resolved.
